const cookieParser = require('cookie-parser');
const express = require('express');
const app = express();
const bcrypt = require("bcrypt"); // it is used to HASHES the password so it cant be reversed(cant be decrypted) .
const jwt = require("jsonwebtoken");

app.use(express.json());
app.use(express.urlencoded({extended:true}));
app.use(cookieParser());

//to work with the bcrypt we need to install :- npm i bcrypt
app.get("/",function(req,res){
    bcrypt.genSalt(10,function(err,salt){               // the salt() method will add some extra random data to the password . to prevent attackers to guessing the password . it generate random string so 2 useer will never have the same password .
       bcrypt.hash("password",salt,function(err,hash){  // the hash() method will take you password and the randome salt and combine them both and create a irreversible hash(string) that cant be deycripted . we never store the real password in DB . we only store the hashed password . 
        console.log(hash);
       });
    });
});

app.get("/compare",function(req,res){
    bcrypt.compare("password","$2b$10$AqdkSS/SmX8NdnXmahiK3eQWY/3ZD6GLj099Ca8yoxjobgZt6/jDS",function(err,result){ //when user login the user entered password is compared with the store hash and this compare() method will response in true and false , to compare password bcrypt internaly again hash the user entered password and check db hash with the new hash and return response . 
        console.log(result);
    });
});

//JWT :- To work with jwt we need to work install :- npm i jsonwebtoken
// It is a string
// Signed by the server
// Sent to the client (browser/mobile app)
// Returned back to server on every request (usually in headers)
// Used to identify the user
// It cannot be decrypted (unless using advanced encryption)
// It can only be verified 

// It has 3 parts:
// Header → algo + type
// Payload → data (like userId, email)
// Signature → proof that token is valid

app.get("/jwt",function(req,res){
    let token = jwt.sign({email: "xyz@eample.com"},"secret");    // this sign() method is used to generate the jwt token , as paremeters it will take the "userData/neccesary data and secrat key" to create the JWT token . and this token is send to browser by the server when user gets login .
    res.cookie("token",token);
    res.send("token has set in cookies . ");
});

app.get("/readJWT",function(req,res){
    let data =  jwt.verify(req.cookies.token,"secret");         // this verify() method is used to verify that the on the request of the logged in user that the token match that was generated by the server .
    console.log(data);
});

app.listen(3000);